# Generated by Django 2.2.4 on 2019-08-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190811_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profi',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Course'),
        ),
        migrations.AddField(
            model_name='profi',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Position'),
        ),
    ]
