# Generated by Django 2.2.4 on 2019-08-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190811_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profi',
            name='courses',
        ),
        migrations.AddField(
            model_name='profi',
            name='courses',
            field=models.ManyToManyField(null=True, to='mysite.Course'),
        ),
    ]
